### ISSUE TITLE
Cannot create new project on pros V5

### ISSUE THREAD

**Issue by ghost** [purduesigbots/pros-atom3#38] opened 2019-02-24 20:02 UTC
Everytime i try to create a new project on Pros for Mac I get this error: 
![image](https://user-images.githubusercontent.com/47671535/53304608-3f745c00-3845-11e9-9ea8-3080a2089160.png)

**Comment by HotelCalifornia** [comment] 2019-02-25 16:18
We're going to need some more information. How did you install PROS?

**Comment by ghost** [comment] 2019-02-25 21:14
@HotelCalifornia 
I am using homebrew method

**Comment by HotelCalifornia** [comment] 2019-02-25 21:15
what commands did you run?

**Comment by ghost** [comment] 2019-02-25 21:40
@HotelCalifornia the ones listed on the website for installation

**Comment by HotelCalifornia** [comment] 2019-02-25 21:42
so `brew cask install pros-editor`?

if so, can you hit `cmd+option+i`, try to make a new project again, and attach a screenshot of the output in the console on the right?

**Comment by ghost** [comment] 2019-02-25 21:47
it was `brew cask install pros-editor`

**Comment by HotelCalifornia** [comment] 2019-02-25 21:47
sorry, that's what I meant. Can you try the other thing I said?

**Comment by ghost** [comment] 2019-02-25 22:02
![screen shot 2019-02-25 at 5 01 20 pm](https://user-images.githubusercontent.com/47671535/53371749-13c5a480-391f-11e9-971d-ca9829475e0a.png)

**Comment by HotelCalifornia** [comment] 2019-02-25 22:07
Try following the instructions from [here](https://pros.cs.purdue.edu/v5/getting-started/macos.html#known-issues):

> If you are using the PROS Editor, open up your init script (File > Init Script) and add the following two lines:
> ```coffee
>  export LANG="en_US.utf-8"
>  export LC_ALL="en_US.utf-8"
>  ```

Then restart the editor.

**Comment by ghost** [comment] 2019-02-25 22:19
![image](https://user-images.githubusercontent.com/47671535/53372675-79b32b80-3921-11e9-8827-4812c2f40df6.png)

**Comment by ghost** [comment] 2019-02-25 22:19
im getting this error ^^^

**Comment by HotelCalifornia** [comment] 2019-02-25 22:20
ahhh... I copied the wrong lines. should be

```coffee
process.env.LANG = 'en_US.utf-8'
process.env.LC_ALL = 'en_US.utf-8'
```

**Comment by ghost** [comment] 2019-02-25 22:23
project can be created as normal but getting this error: 

![image](https://user-images.githubusercontent.com/47671535/53372906-15dd3280-3922-11e9-9c06-5841ecd62bf8.png)

**Comment by ghost** [comment] 2019-02-25 22:24
correction*** i can create the project!!

**Comment by HotelCalifornia** [comment] 2019-02-25 22:25
The other issue is the same as #37. Since the original problem seems to have been solved, I'm going to close this one.

**Closed as completed by HotelCalifornia** 2019-02-25 22:25 UTC
Labels: question

**Comment by ghost** [comment] 2019-02-25 22:26
@HotelCalifornia thank you!!! you are a lifesaver :)

**Comment by edjubuh** [comment] 2019-02-25 22:29
If you could help us out in reproducing/debugging #37 that would be greatly appreciated. Neither of us are able to reproduce the issue.

**Comment by ghost** [comment] 2019-02-25 22:36
@edjubuh how can i help?

**Comment by edjubuh** [comment] 2019-02-25 22:37
https://github.com/purduesigbots/pros-atom3/issues/37#issuecomment-466728224
