### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by JuicetinAn** [purduesigbots/pros-atom3#43] opened 2020-03-18 22:43 UTC
[Enter steps to reproduce:]

1. Download Pros Through Homebrew
2. After finish Downloading, open a new project for Pros 

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Mac OS X 10.15.3
**Thrown From**: [pros-atom3](https://github.com/purduesigbots/pros-atom3) package 1.1.0

### Stack Trace

Uncaught SyntaxError: Unexpected end of JSON input

```
At file:///Applications/PROS%20Editor.app/Contents/Resources/app.asar/static/index.html:1

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /packages/pros-atom3/node_modules/@purduesigbots/pros-cli-middleware/dist/util.js:110:38)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:246:13)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```

### Commands

```
  4x -9:48.8.0 core:move-down (input.hidden-input)
     -9:44.8.0 core:confirm (input.hidden-input)
  2x -9:44.8.0 pros:build (ul.list-inline.tab-bar.inset-panel)
     -9:23.8.0 pros:upload (atom-pane.pane.active)
     -9:18.6.0 find-and-replace:show (atom-pane.pane.active)
     -9:13.4.0 application:open (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
  2x -8:52.7.0 pros:new-project (atom-pane.pane.active)
     -1:13.3.0 application:open (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -1:08.8.0 pros:new-project (button.btn.btn-primary)
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
busy 0.7.0 
busy-signal 2.0.1 
file-icons 2.1.39 
ide-cquery 0.14.0 
minimap 4.29.9 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-selection 4.5.0 
pros-atom3 1.1.0 
terminal-tab-plus 0.5.11 
tool-bar 1.2.2 
tool-bar-main 0.0.12 
```

**Comment by kunwarsahni01** [comment] 2020-03-19 00:34
This seems to be a duplicate of #37

**Closed as completed by kunwarsahni01** 2020-03-19 00:35 UTC
